environment:
  NodeVersion: 8
  SLBuildDirectory: streamlabs-build
  SLRuntime: electron
  SLRuntimeVersion: 1.7.11
  SLGenerator: Visual Studio 14 2015 Win64
  SLDistributeDirectory: distribute
  SLArch: x64
  SLArtifact: streamlabs-x86_64
  
install:
  - ps: Install-Product node $env:NodeVersion
  - yarn install

build_script:
  - yarn run cmake-js configure --out "%SLBuildDirectory%" -r="%SLRuntime%" -v="%SLRuntimeVersion%" -G"%SLGenerator%" -a "%SLArch%" --CDCMAKE_INSTALL_PREFIX="%SLDistributeDirectory%"
  - cmake --build %SLBuildDirectory% --target install --config Release

after_build:
  - 7z a "%SLArtifact%.tar" "%SLBuildDirectory%\%SLDistributeDirectory%\*"
  - 7z a "%SLArtifact%.tar.gz" "%SLArtifact%.tar"

artifacts:
  - path: $(SLArtifact)
    name: Streamlabs Aritfact

test: off